name: Generated APK AAB

env:
  main_project_module: app
  ANDROID_PROJECT_DIR: zal_app

on:
  workflow_dispatch:
  push:
    branches: [ master, test ]
    paths:
      - 'zal_app/**'
      - '.github/workflows/check-android.yml'
  pull_request:
    paths:
      - 'zal_app/**'
      - '.github/workflows/check-android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease
        working-directory: ${{ env.ANDROID_PROJECT_DIR }}
